name: Test data output as json

on:
  push:
    branches:
      - introduce-measurement-output # for testing purposes only on this branch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize Energy Estimation
        uses: ./
        with:
          task: start-measurement

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Node Setup Energy Measurment
        id: data-node-setup
        uses: ./
        with:
          task: get-measurement
          label: 'node setup'
          send-data: false

      - name: Print node setup data
        run: |
          echo "total json: ${{ steps.data-node-setup.outputs.data-lap-json }}"

      - name: Assert node setup output is appropriate
        shell: bash
        run: |
          if [ '${{ steps.data-node-setup.outputs.data-lap-json }}' == '' ]; then
            echo "Output must not be empty"; exit 1;
          fi
          if [!$(echo '${{ steps.data-node-setup.outputs.data-lap-json }}' | jq 'has("repository", "branch", "workflow", "run_id", "label", "cpu_avg_percent", "energy_joules", "power_avg_watts") and length == 8')]; then
            echo "output has wrong structure"; exit 1;
          fi
          if [!$(echo '${{ steps.data-node-setup.outputs.data-lap-json }}' | jq '.label == "node setup"')]; then
            echo "value of 'label' must be 'node setup'"; exit 1;
          fi

      - name: Wait before the next step
        run: sleep 10

      - name: Sleep measurement
        id: data-sleep
        uses: ./
        with:
          task: get-measurement
          label: "sleep"
          send-data: false

      - name: Print sleep data
        run: |
          echo "total json: ${{ steps.data-sleep.outputs.data-lap-json }}"

      - name: Assert sleep output is appropriate
        shell: bash
        run: |
          if [ '${{ steps.data-sleep.outputs.data-lap-json }}' == '' ]; then
            echo "Output must not be empty"; exit 1;
          fi
          if [!$(echo '${{ steps.data-sleep.outputs.data-lap-json }}' | jq 'has("repository", "branch", "workflow", "run_id", "label", "cpu_avg_percent", "energy_joules", "power_avg_watts") and length == 8')]; then
            echo "output has wrong structure"; exit 1;
          fi
          if [!$(echo '${{ steps.data-sleep.outputs.data-lap-json }}' | jq '.label == "sleep"')]; then
            echo "value of 'label' must be 'sleep'"; exit 1;
          fi

      - name: Eco CI Energy Estimation
        id: data-total
        uses: ./
        with:
          task: display-results
          send-data: false

      - name: Print total data
        run: |
          echo "total json: ${{ steps.data-total.outputs.data-total-json }}"

      - name: Assert total output is appropriate
        shell: bash
        run: |
          if [ '${{ steps.data-total.outputs.data-total-json }}' == '' ]; then
            echo "Output must not be empty"; exit 1;
          fi
          if [!$(echo '${{ steps.data-total.outputs.data-total-json }}' | jq 'has("repository", "branch", "workflow", "run_id", "label", "cpu_avg_percent", "energy_joules", "power_avg_watts") and length == 8')]; then
            echo "output has wrong structure"; exit 1;
          fi
